config/routes.rb
Rails.application.routes.draw do

  resources :bollywoods
  resources :hollywoods
  resources :footballs
  resources :leaderboards
  resources :crickets
  get 'home/index'
  get 'start/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations: 'users/registrations'}
  # devise_scope :user do
  # 	delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_fuser_session
  # 	get 'sign_in', :to => 'users/sessions#new', :as => :new_fuser_session
  # end	
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
  belongs_to :user
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :set_leaderboard, only: [:show, :edit, :update, :destroy]

  # GET /leaderboards
  # GET /leaderboards.json
  def index
    @lbord = Leaderboard.find_by_user_id(current_user.id)
    @sports = Leaderboard.order('maxfootscore+maxcricscore DESC')
    @movies = Leaderboard.order('maxbollyscore+maxhollyscore DESC')
  end

  # GET /leaderboards/1
  # GET /leaderboards/1.json
  def show
  end

  # GET /leaderboards/new
  def new
    @leaderboard = Leaderboard.new
  end

  # GET /leaderboards/1/edit
  def edit
  end

  # POST /leaderboards
  # POST /leaderboards.json
  def create
    @leaderboard = Leaderboard.new(leaderboard_params)
    
    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully created.' }
        format.json { render :show, status: :created, location: @leaderboard }
      else
        format.html { render :new }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderboards/1
  # PATCH/PUT /leaderboards/1.json
  def update
    respond_to do |format|
      if @leaderboard.update(leaderboard_params)
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @leaderboard }
      else
        format.html { render :edit }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderboards/1
  # DELETE /leaderboards/1.json
  def destroy
    @leaderboard.destroy
    respond_to do |format|
      format.html { redirect_to leaderboards_url, notice: 'Leaderboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaderboard
      @leaderboard = Leaderboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leaderboard_params
      params.require(:leaderboard).permit(:user_id, :cricketscore, :footballscore, :bollywoodscore, :hollywoodscore)
    end
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/leaderboards/_form.html.erb
<%= form_with(model: leaderboard, local: true) do |form| %>
  <% if leaderboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
      <% leaderboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :leaderboard_user_id %>
  </div>

  <div class="field">
    <%= form.label :cricketscore %>
    <%= form.number_field :cricketscore, id: :leaderboard_cricketscore %>
  </div>

  <div class="field">
    <%= form.label :footballscore %>
    <%= form.number_field :footballscore, id: :leaderboard_footballscore %>
  </div>

  <div class="field">
    <%= form.label :bollywoodscore %>
    <%= form.number_field :bollywoodscore, id: :leaderboard_bollywoodscore %>
  </div>

  <div class="field">
    <%= form.label :hollywoodscore %>
    <%= form.number_field :hollywoodscore, id: :leaderboard_hollywoodscore %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leaderboards/edit.html.erb
<h1>Editing Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Show', @leaderboard %> |
<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/index.html.erb
<h4 style="text-align:center; color:red"> Your current score in 'Sports quiz' is <%= @lbord.footballscore+@lbord.cricketscore %></h4>
<div class="container">
<table class="table table-striped table-bordered">
<thead> 
<tr><th>Email</th>
<th> Score(max) </th></tr></thead>
<tbody>
<% @sports.each do |sport| %>
  <tr>
  <td><%= User.find(sport.user_id).email %></td>
  <td><%= sport.maxfootscore+sport.maxcricscore %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

<h4 style="text-align:center; color:red"> Your current score in 'Movies quiz' is <%= @lbord.hollywoodscore+@lbord.bollywoodscore %></h4>
<div class="container">
<table class="table table-striped table-bordered">
<thead> 
<tr><th>Email</th>
<th> Score(max) </th></tr></thead>
<tbody>
<% @movies.each do |movie| %>
  <tr>
  <td><%= User.find(movie.user_id).email %></td>
  <td><%= movie.maxhollyscore+movie.maxbollyscore %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/leaderboards/new.html.erb
<h1>New Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/show.html.erb
<p>
  <strong>User:</strong>
  <%= @leaderboard.user %>
</p>

<p>
  <strong>Cricketscore:</strong>
  <%= @leaderboard.cricketscore %>
</p>

<p>
  <strong>Footballscore:</strong>
  <%= @leaderboard.footballscore %>
</p>

<p>
  <strong>Bollywoodscore:</strong>
  <%= @leaderboard.bollywoodscore %>
</p>

<p>
  <strong>Hollywoodscore:</strong>
  <%= @leaderboard.hollywoodscore %>
</p>

<%= link_to 'Edit', edit_leaderboard_path(@leaderboard) %> |
<%= link_to 'Back', leaderboards_path %>