config/routes.rb
Rails.application.routes.draw do

  resources :bollywoods
  resources :hollywoods
  resources :footballs
  resources :leaderboards
  resources :crickets
  get 'home/index'
  get 'start/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations: 'users/registrations'}
  # devise_scope :user do
  # 	delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_fuser_session
  # 	get 'sign_in', :to => 'users/sessions#new', :as => :new_fuser_session
  # end	
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hollywood.rb
class Hollywood < ApplicationRecord
end

app/controllers/hollywoods_controller.rb
class HollywoodsController < ApplicationController
  before_action :set_hollywood, only: [:show, :edit, :update, :destroy]

  # GET /hollywoods
  # GET /hollywoods.json
  def index
    @lbord = Leaderboard.find_by_user_id(current_user.id)
    @leadbord = Leaderboard.find_by_user_id(current_user.id)
    @holywoods = Leaderboard.order('maxhollyscore DESC')
    if @leadbord.hollywoodques == Hollywood.count
      @leadbord.hollywoodscore = 0
      @leadbord.hollywoodques = 0
      @leadbord.save
    end
  end

  # GET /hollywoods/1
  # GET /hollywoods/1.json
  def show
    @lbord = Leaderboard.find_by_user_id(current_user.id)
    @goto = '/hollywoods/' + (Integer(params[:id])+1).to_s
    @lbord.checkh = true
    if (Integer(params[:id])==1)
      @lbord.hollywoodscore = 0
    end
    if (Integer(params[:id])!=1 && ((Integer(params[:id])!=@lbord.hollywoodques+1) && (Integer(params[:id])!=@lbord.hollywoodques)))
      @got = '/hollywoods/' + (@lbord.hollywoodques).to_s
      print(@got)
      redirect_to @got
    else
      @lbord.hollywoodques=Integer(params[:id])
      @lbord.save
      @str = ''
      if @hollywood
        if @hollywood.multicheck
          if(params[:A])
            @str += 'A'
          end
          if(params[:B])
            @str += 'B'
          end 
          if(params[:C])
            @str += 'C'
          end
          if(params[:D])
            @str += 'D'
          end
        else
          if(params[:m])
            @str = params[:m]
          end
        end
        print("hi")
        print(@str)
        print("hello")
        print(@hollywood.correctans)
        if @str == @hollywood.correctans
          @lbord.hollywoodscore += 20
          if @lbord.hollywoodscore > @lbord.maxhollyscore
            @lbord.maxhollyscore = @lbord.hollywoodscore
          end
          @lbord.save
        end
        if params[:A] || params[:B] || params[:C] || params[:D] || params[:m]
          if Integer(params[:id]) == Hollywood.count
            redirect_to '/hollywoods/'
          else
             redirect_to @goto
          end
        end
      else
        @lbord.hollywoodscore = 0
        @lbord.hollywoodques = 0
        @lbord.save
        redirect_to root_path
      end
    end
  end   

  # GET /hollywoods/new
  def new
    @hollywood = Hollywood.new
  end

  # GET /hollywoods/1/edit
  def edit
  end

  # POST /hollywoods
  # POST /hollywoods.json
  def create
    @hollywood = Hollywood.new(hollywood_params)

    respond_to do |format|
      if @hollywood.save
        format.html { redirect_to @hollywood, notice: 'Hollywood was successfully created.' }
        format.json { render :show, status: :created, location: @hollywood }
      else
        format.html { render :new }
        format.json { render json: @hollywood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hollywoods/1
  # PATCH/PUT /hollywoods/1.json
  def update
    respond_to do |format|
      if @hollywood.update(hollywood_params)
        format.html { redirect_to @hollywood, notice: 'Hollywood was successfully updated.' }
        format.json { render :show, status: :ok, location: @hollywood }
      else
        format.html { render :edit }
        format.json { render json: @hollywood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hollywoods/1
  # DELETE /hollywoods/1.json
  def destroy
    @hollywood.destroy
    respond_to do |format|
      format.html { redirect_to hollywoods_url, notice: 'Hollywood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hollywood
      if(Integer(params[:id]) <= Hollywood.count)
        @hollywood = Hollywood.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hollywood_params
      params.require(:hollywood).permit(:question, :opta, :optb, :optc, :optd, :correctans)
    end
end

app/helpers/hollywoods_helper.rb
module HollywoodsHelper
end

app/views/hollywoods/_form.html.erb
<%= form_with(model: hollywood, local: true) do |form| %>
  <% if hollywood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hollywood.errors.count, "error") %> prohibited this hollywood from being saved:</h2>

      <ul>
      <% hollywood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :hollywood_question %>
  </div>

  <div class="field">
    <%= form.label :opta %>
    <%= form.text_field :opta, id: :hollywood_opta %>
  </div>

  <div class="field">
    <%= form.label :optb %>
    <%= form.text_field :optb, id: :hollywood_optb %>
  </div>

  <div class="field">
    <%= form.label :optc %>
    <%= form.text_field :optc, id: :hollywood_optc %>
  </div>

  <div class="field">
    <%= form.label :optd %>
    <%= form.text_field :optd, id: :hollywood_optd %>
  </div>

  <div class="field">
    <%= form.label :correctans %>
    <%= form.text_field :correctans, id: :hollywood_correctans %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hollywoods/edit.html.erb
<h1>Editing Hollywood</h1>

<%= render 'form', hollywood: @hollywood %>

<%= link_to 'Show', @hollywood %> |
<%= link_to 'Back', hollywoods_path %>

app/views/hollywoods/index.html.erb
<%= link_to "Start the quiz!!!", '/hollywoods/1',  class: "btn btn-info" %>
<% if @lbord.hollywoodques > 0 %>
  <% if @lbord.hollywoodques != Football.count %>
    <%= link_to "resume", '/hollywoods/' + (@lbord.hollywoodques).to_s,  class: "btn btn-info" %>
  <% end %>
<% end %>

<h4 style="text-align:center; color:red"> Your current score in 'hollywood quiz' is <%= @lbord.hollywoodscore %></h4>
<div class="container">
<table class="table table-striped table-bordered">
<thead> 
<tr><th>Email</th>
<th> Score(max) </th></tr></thead>
<tbody>
<% @holywoods.each do |holywood| %>
  <tr>
  <td><%= User.find(holywood.user_id).email %></td>
  <td><%= holywood.maxhollyscore %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/hollywoods/new.html.erb
<h1>New Hollywood</h1>

<%= render 'form', hollywood: @hollywood %>

<%= link_to 'Back', hollywoods_path %>

app/views/hollywoods/show.html.erb
<form method="GET" action= "#">
  <div class="container">
  <div class="question">
  <span class="label label-warning"><%= @hollywood.id %></span>
     <span class="question">
    <strong>Question:</strong>
    <%= @hollywood.question %>
  </span>
  </div>
  <ol type="a">
  <% if @hollywood.multicheck %>
    <span style="color:red">Multi correct question </span><br />
    <li>
    <div style="padding: 2em; border: 1px solid">
    <%= check_box_tag(:A) %>
    <%= label_tag(:A, @hollywood.opta) %>
    </div>
      </li>
      <li>
          <div style="padding: 2em; border: 1px solid">
    <%= check_box_tag(:B) %>
    <%= label_tag(:B, @hollywood.optb) %>
    </div>
      </li>
      <li>
          <div style="padding: 2em; border: 1px solid">
      <%= check_box_tag(:C) %><%= label_tag(:C, @hollywood.optc) %>
      </li>
      <li>
          <div style="padding: 2em; border: 1px solid">
      <%= check_box_tag(:D) %><%= label_tag(:D, @hollywood.optd) %>
      </li>
    </ol>
  <% else %>
      <span style="color:red">Single Correct type question</span><br />
    <li>
      <!-- <div class="choice"> -->
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="A"><%= @hollywood.opta %></input> 
      </div>
    </li>
    <li>
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="B"><%= @hollywood.optb %></input> 
      </div>
    </li>
    <li>
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="C"><%= @hollywood.optc %></input> 
      </div>
    </li>
    <li>
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="D"><%= @hollywood.optd %></input> 
      </div>
    </li>
  <% end %>
  <div class="container" style="text-align: center">
  <div class="btn btn-success">
  <input type="submit">
  </div>
  </div>

  <h3 style="text-align:center; color:red"> Current score: <%= @lbord.hollywoodscore %></p>
</form>