config/routes.rb
Rails.application.routes.draw do

  resources :bollywoods
  resources :hollywoods
  resources :footballs
  resources :leaderboards
  resources :crickets
  get 'home/index'
  get 'start/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations: 'users/registrations'}
  # devise_scope :user do
  # 	delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_fuser_session
  # 	get 'sign_in', :to => 'users/sessions#new', :as => :new_fuser_session
  # end	
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cricket.rb
class Cricket < ApplicationRecord
end

app/controllers/crickets_controller.rb
class CricketsController < ApplicationController
  before_action :set_cricket, only: [:show, :edit, :update, :destroy]

  # GET /crickets
  # GET /crickets.json
  def index
    @lbord = Leaderboard.find_by_user_id(current_user.id)
    @leadbord = Leaderboard.find_by_user_id(current_user.id)
    @crikets = Leaderboard.order('maxcricscore DESC')
    if @leadbord.cricketques == Cricket.count
      @leadbord.cricketscore = 0
      @leadbord.cricketques = 0
      @leadbord.save
    end
  end

  # GET /crickets/1
  # GET /crickets/1.json
  def show
    @lbord = Leaderboard.find_by_user_id(current_user.id)
    @goto = '/crickets/' + (Integer(params[:id])+1).to_s
    @lbord.checkc = true
    if (Integer(params[:id])==1)
      @lbord.cricketscore = 0
    end
    if (Integer(params[:id])!=1 && ((Integer(params[:id])!=@lbord.cricketques+1) && (Integer(params[:id])!=@lbord.cricketques)))
      @got = '/crickets/' + (@lbord.cricketques).to_s
      print(@got)
      redirect_to @got
    else
      @lbord.cricketques=Integer(params[:id])
      @lbord.save
      @str = ''
      if @cricket
        if @cricket.multicheck
          if(params[:A])
            @str += 'A'
          end
          if(params[:B])
            @str += 'B'
          end 
          if(params[:C])
            @str += 'C'
          end
          if(params[:D])
            @str += 'D'
          end
        else
          if(params[:m])
            @str = params[:m]
          end
        end
        print("hi")
        print(@str)
        print("hello")
        print(@cricket.correctans)
        if @str == @cricket.correctans
          @lbord.cricketscore += 20
          if @lbord.cricketscore > @lbord.maxcricscore
            @lbord.maxcricscore = @lbord.cricketscore
          end
          @lbord.save
        end
        if params[:A] || params[:B] || params[:C] || params[:D] || params[:m]
          if Integer(params[:id]) == Cricket.count
            redirect_to '/crickets/'
          else
             redirect_to @goto
          end
        end
      else
        @lbord.cricketscore = 0
        @lbord.cricketques = 0
        @lbord.save
        redirect_to root_path
      end
    end
  end   
  # GET /crickets/new
  def new
    @cricket = Cricket.new
  end

  # GET /crickets/1/edit
  def edit
  end

  # POST /crickets
  # POST /crickets.json
  def create
    @cricket = Cricket.new(cricket_params)

    respond_to do |format|
      if @cricket.save
        format.html { redirect_to @cricket, notice: 'Cricket was successfully created.' }
        format.json { render :show, status: :created, location: @cricket }
      else
        format.html { render :new }
        format.json { render json: @cricket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crickets/1
  # PATCH/PUT /crickets/1.json
  def update
    respond_to do |format|
      if @cricket.update(cricket_params)
        format.html { redirect_to @cricket, notice: 'Cricket was successfully updated.' }
        format.json { render :show, status: :ok, location: @cricket }
      else
        format.html { render :edit }
        format.json { render json: @cricket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crickets/1
  # DELETE /crickets/1.json
  def destroy
    @cricket.destroy
    respond_to do |format|
      format.html { redirect_to crickets_url, notice: 'Cricket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cricket
      if(Integer(params[:id]) <= Cricket.count)
        @cricket = Cricket.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cricket_params
      params.require(:cricket).permit(:question, :opta, :optb, :optc, :optd, :correctans)
    end
end

app/helpers/crickets_helper.rb
module CricketsHelper
end

app/views/crickets/_form.html.erb
<%= form_with(model: cricket, local: true) do |form| %>
  <% if cricket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cricket.errors.count, "error") %> prohibited this cricket from being saved:</h2>

      <ul>
      <% cricket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :cricket_question %>
  </div>

  <div class="field">
    <%= form.label :opta %>
    <%= form.text_field :opta, id: :cricket_opta %>
  </div>

  <div class="field">
    <%= form.label :optb %>
    <%= form.text_field :optb, id: :cricket_optb %>
  </div>

  <div class="field">
    <%= form.label :optc %>
    <%= form.text_field :optc, id: :cricket_optc %>
  </div>

  <div class="field">
    <%= form.label :optd %>
    <%= form.text_field :optd, id: :cricket_optd %>
  </div>

  <div class="field">
    <%= form.label :correctans %>
    <%= form.text_field :correctans, id: :cricket_correctans %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crickets/cricket_leaderboard_show.html.erb
<h4> Your current score in 'cricket quiz' is <=% @lbord.cricketscore %></h4>

<table>
<thead> 
<tr><th>Email</th>
<th> Score(max) </th></tr></thead>
<tbody>
<% @crikets.each do |criket| %>
	<tr>
	<td><%= User.find(criket.user_id).email %></td>
	<td>@cricket.maxcricscore</td>
	</tr>
<%= end %>
</tbody>
</table>

app/views/crickets/edit.html.erb
<h1>Editing Cricket</h1>

<%= render 'form', cricket: @cricket %>

<%= link_to 'Show', @cricket %> |
<%= link_to 'Back', crickets_path %>

app/views/crickets/index.html.erb
<%= link_to "Start the quiz!!!", '/crickets/1',  class: "btn btn-info" %>
<% if @lbord.cricketques > 0 %>
  <% if @lbord.cricketques != Cricket.count %>
    <%= link_to "resume", '/crickets/' + (@lbord.cricketques).to_s,  class: "btn btn-info" %>
  <% end %>
<% end %>

<h4 style="text-align:center; color:red"> Your current score in 'cricket quiz' is <%= @lbord.cricketscore %></h4>
<div class="container">
<table class="table table-striped table-bordered">
<thead> 
<tr><th>Email</th>
<th> Score(max) </th></tr></thead>
<tbody>
<% @crikets.each do |criket| %>
  <tr>
  <td><%= User.find(criket.user_id).email %></td>
  <td><%= criket.maxcricscore %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/crickets/new.html.erb
<h1>New Cricket</h1>

<%= render 'form', cricket: @cricket %>

app/views/crickets/show.html.erb
<form method="GET" action= "#">
  <div class="container">
  <div class="question">
  <span class="label label-warning"><%= @cricket.id %></span>
     <span class="question">
    <strong>Question:</strong>
    <%= @cricket.question %>
  </span>
  </div>
  <ol type="a">
  <% if @cricket.multicheck %>
    <span style="color:red">Multi correct question </span><br />
    <li>
    <div style="padding: 2em; border: 1px solid">
    <%= check_box_tag(:A) %>
    <%= label_tag(:A, @cricket.opta) %>
    </div>
      </li>
      <li>
          <div style="padding: 2em; border: 1px solid">
    <%= check_box_tag(:B) %>
    <%= label_tag(:B, @cricket.optb) %>
    </div>
      </li>
      <li>
          <div style="padding: 2em; border: 1px solid">
      <%= check_box_tag(:C) %><%= label_tag(:C, @cricket.optc) %>
      </li>
      <li>
          <div style="padding: 2em; border: 1px solid">
      <%= check_box_tag(:D) %><%= label_tag(:D, @cricket.optd) %>
      </li>
    </ol>
  <% else %>
      <span style="color:red">Single Correct type question</span><br />
    <li>
      <!-- <div class="choice"> -->
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="A"><%= @cricket.opta %></input> 
      </div>
    </li>
    <li>
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="B"><%= @cricket.optb %></input> 
      </div>
    </li>
    <li>
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="C"><%= @cricket.optc %></input> 
      </div>
    </li>
    <li>
      <div style="padding: 2em; border: 1px solid">
      <input type="radio" name="m" value="D"><%= @cricket.optd %></input> 
      </div>
    </li>
  <% end %>
  <div class="container" style="text-align: center">
  <div class="btn btn-success">
  <input type="submit">
  </div>
  </div>

  <h3 style="text-align:center; color:red"> Current score: <%= @lbord.cricketscore %></p>
</form>