config/routes.rb
Rails.application.routes.draw do

  resources :bollywoods
  resources :hollywoods
  resources :footballs
  resources :leaderboards
  resources :crickets
  get 'home/index'
  get 'start/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations: 'users/registrations'}
  # devise_scope :user do
  # 	delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_fuser_session
  # 	get 'sign_in', :to => 'users/sessions#new', :as => :new_fuser_session
  # end	
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	# puts "hi	"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container" style="text-align: center"><h1>Welcome to the quizapp</h1></div>
<div class="container-fluid" style="text-align : center">
<% if current_user %>
	<%= link_to "Leaderboard", leaderboards_path, class: "btn btn-success" %>
	<% if current_user.admin==true %>
		<%= link_to "Admin Page", rails_admin_path , class: "btn btn-success" %>
	<% end %><br /><br />
	<%= link_to "Logout", destroy_user_session_path, method: :delete , class: "btn btn-success" %><br /><br />	
	<%= link_to "Start The Quiz Page", start_index_path, class: "btn btn-success" %><br /><br />
<% else %>
<%= link_to "Login", new_user_session_path , class: "btn btn-info" %><br /><br />
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info"  %><br /><br />
<% end %>
</div>